### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ghost** [srinathh/mobilehtml5app#1]
Is the golang "server" running on the mobile ? 
I would like to try this out, but just wanted to check.

Btw i also did the  Aswan to Luxor trip on a faluka. Amazing...

**Comment by srinathh** [comment]
yup - the server is running on mobile. 

At some point, i plan to create a simpler architecture to not require a server but rely on simple message passing to transmit a requests since starting and stopping the server makes this slower than I would like. Doing this requires richer resource call interception funcitons for transmitting headers appropriately which is available in Chromium Webview onwards (Kit Kat & above). I am also thinking of dropping CrossWalk support for simplicity since Kit Kat and above which contain Chromium Webview that has the functions to support richer header data in "non-server" mode is now > 80%

There are also some bugs in Android gradle command line build which if resolved will make this project much cleaner. The bug was recently accepted and assigned a priority.
https://code.google.com/p/android/issues/detail?id=209352#

**Comment by ghost** [comment]
thanks for the info. Really appreciate it.

Regarding the proposed way of passing data from the "server" to the GUI, can you elaborate on this please.  Whats your proposed way ? AM super curious.
I have tried GRPC, and its pretty awesome, but i find it also pretty complex ot get going and allot going on under the hood.
There is also Vanadium (https://vanadium.github.io/core.html), by google, which i have been using.
Its RPC is here: https://vanadium.github.io/concepts/rpc.html. Its very simple and works well and talks to WebView. 
This is the best repo to look at: https://github.com/vanadium/core
The other repos are valid, but they are going through a refactoring of lots into core.

Also, I used standard http in the past (which is what your currently doing), and did not find the performance to be too bad. But i did not test it allot i admit. It was more of a test harness to play around with the potential of this architecture.

I agree with the dropping of crosswalk. I did not knwo that kit kat and above version is at 80%.

**Comment by srinathh** [comment]
Thanks for sharing the links.

Actually there's a much simpler way of passing information between WebView & the Go language routines than RPC. gomobile basically supports compiling the Go language routines to a java importable library. The idea is to simply export a function that can receive request data from Java (intercepting the WebView request), create a request & responsewriter and call DefaultServeMux or whatever router is being used (since Routers themselves are http.Handlers). The data returned in responsewriter can then be returned by this function to the Java side which sends it to WebView.

This way, there's no overhead of processes, RPC or Socket I/O - only simple function calls. In the ideal case, the HTTP "server" would be stateless and purely functional. For instance level persistence, the init() function can instantiate global data structures. For permanent persistence, disk/file based I/O, databases or cloud connections as appropriate.

**Comment by ghost** [comment]
Hey 
cool...

Ok i got ya. I agree. No sockets, but just memory  pointers is lower overhead for sure.

I avoided it for two reasons so far:
1. I read that they had some issues with the binding stuff with gomobile, and kind of avoided it.
1. Also i was biased. in that i actually wanted a golang backend that i can stick on the server OR on a mobile phone, and they both communicate with the GUI over http.

But i think its good for certain situations.

at the moment i am playing with flutter and vanadium together.

**Comment by joeblew99** [comment]
There are e samples using grpc out there now.

I am trying it out with your basic setup.

Grpc has some advantages. 

I am also planning on using json patch.
This will make the web code much simpler
