### ISSUE TITLE
Without react

### ISSUE THREAD

**Issue by joeblew99** [srinathh/mobilehtml5app#3]
https://github.com/murlokswarm/app. 

Might be interesting for you.

I am looking at your repo with a view to using some of the code to get going on the android and iOS port.

**Comment by srinathh** [comment]
Thanks for sharing and very interesting to see. Looking at the code, the
concept seems to be constructing composable components like React but with
event handling in Go  - am I right?

My approach has been towards writing UI code also primarily in JS to be
able to reuse the UI framework zoo that exists :-)

Regards
Srinath



On Feb 5, 2017 3:04 PM, "jow blew" <notifications@github.com> wrote:

https://github.com/murlokswarm/app.

Might be interesting for you.

I am looking at your repo with a view to using some of the code to get
going on the android and iOS port.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/srinathh/mobilehtml5app/issues/3>, or mute the thread

**Comment by joeblew99** [comment]
yes your spot on.

I know what you mean about the UI zoo.
I instead use this:
https://github.com/material-components
Because its independent of lifecycle complexity it makes it easy to make it do what you want.



I really like its pragmatics of murlok 
DO you want to help on android ?
https://github.com/murlokswarm/android

I raised an issue on the design aspects.
